CREATE TABLE Account (
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Item (
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	AccountId INT NOT NULL FOREIGN KEY REFERENCES Account (Id) ON DELETE CASCADE
);

INSERT INTO Account (Name) VALUES
	('Nick');